### ISSUE TITLE
Force Override Approval

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#147]
Allow approval of a pull request with just one approval and by the pull request submitter.

* must be a special additional keyword, e.g. :boom: 
* must be an additional configuration option in .zappr.yml

Example:
```yaml
approvals:
  minimum: 1
  pattern: ":\\+1:"
  override: ":boom:"
```
