### ISSUE TITLE
Commit message patterns. Turn off default merge.

### ISSUE THREAD

**Issue by rbarilani** [zalando/zappr#342]
I would like to have a way to really force one commit convention.
Right now if you have a ZAPPR server that has default commit message patterns, those patterns are merged with the patterns provided by the .zappr.yaml contained in the repository.

This means that if one of the pattern pass the commit is valid. So basically when you have the default in your zappr server, you can't enforce a commit convention.

I can think of something like:

```yaml
commit:
  message:
    default_patterns: false
    patterns:
      - "^(feat|fix|docs|style|refactor|perf|test|chore)\\(.*\\):.*(MCFE|MCOMS)-[0-9]+"
```

The ```default_patterns: false``` will prevent the merging the default patterns defined on the zappr server.

@prayerslayer WDYT?
