### ISSUE TITLE
Enterprise: make length check optional for specification

### ISSUE THREAD

**Issue by gagoman** [zalando/zappr#365]
This change is **BREAKING**

We need to be able to:

* Toggle length check
* Set required length

Proposed configuration is:

````
specification:
  title:
    minimum-length:
      enabled: true
      length: 8
  body:
    minimum-length:
      enabled: true
      length: 8
    contains-url: true
    contains-issue-number: true
````

Required changes:

- [x] Error message (length is not a required one and can not be used to build error message)
- [x] Configuration
