### ISSUE TITLE
OneOf Labels Check

### ISSUE THREAD

**Issue by drummerwolli** [zalando/zappr#562]
in the label check config, it should be possible to define an array of labels, where just one label needs to be matched for the check to be fulfilled. config could look something like this:

```
pull-request:
  labels:
    # pull request cannot be merged without these labels (one match is enough)
    oneOf:
      - merge to dev
      - merge to live
    # pull request cannot be merged without these labels (all need to be matched)
    required:      
      - reviewed
```
(this example config also demonstrates my use-case, i want to to make it mandatory to indicate which branch you want to merge to)
(trying to maintain backwards compatibility, naming can be adjusted, of course)
