### ISSUE TITLE
Approval/veto regexes only work for start of comment

### ISSUE THREAD

**Issue by itsthejb** [zalando/zappr#582]
Hi there,

Trying to use the following config:

```
approvals:
  minimum: 2
  pattern: ":\\+1:|:pray:|:shipit:|👍|🙏|✅"
  veto:
    pattern: ":\\-1:|👎|❌" # must contain thumbs down or other
```

i.e. the approvals/vetos can occur anywhere in the comment, not necessarily the start (by removing anchors). This however, appears not to work, even though there would seem to be no limitation on this [here](https://github.com/zalando/zappr/blob/3d0124477e2dfdf505885c375a10c6392f49b50b/server/checks/Approval.js#L239).

It would be nice to have this for more expressive messages.

Hope someone can help!
