### ISSUE TITLE
Incorrectly reported failed check name 'contains-issue-number'

### ISSUE THREAD

**Issue by Dmitry-Erokhin** [zalando/zappr#595]
### Context
```yaml
specification:
  title:
    minimum-length:
      enabled: true
      length: 8
  body:
    minimum-length:
      enabled: true
      length: 8
    contains-url: false
    contains-issue-number: false
    template:
      differs-from-body: false
```

### Trigger
Open PR with "plz" as a PR body message

### Current behaviour
Reported "PR body failed check 'contains-issue-number'"

### Expected behaviour
Reported "PR body failed check 'minimum-length'" (or something like this, identifying that length is not fulfill requirements)

### Description
![Screenshot 2020-05-14 at 11 37 25](https://user-images.githubusercontent.com/283266/81920482-8cbf2380-95d9-11ea-89eb-dd728de0a73e.png)

![Screenshot 2020-05-14 at 11 38 19](https://user-images.githubusercontent.com/283266/81920522-99437c00-95d9-11ea-99ab-e106a09e7c84.png)
